### ISSUE TITLE
BioProject metadata can not be found under BioProject PRJNA792450

### ISSUE THREAD

**Issue by dctongsheng** [miramou/pe_cfrna#1]
I'm very interested, but can't find clinical data，Thank you very much if you can provide a link

**Comment by miramou** [comment]
You can find clinical metadata under the SRA run selector or if you prefer, you can also browse per sample. Here's a link - [https://www.ncbi.nlm.nih.gov/Traces/study/?acc=SRP352519&o=acc_s%3Aa](https://www.ncbi.nlm.nih.gov/Traces/study/?acc=SRP352519&o=acc_s%3Aa)
