### ISSUE TITLE
Data normalization for ML

### ISSUE THREAD

**Issue by davidwumdphd** [miramou/pe_cfrna#3]
Dear Dr. Moufarrej,

Thanks for your wonderful paper and code! 

Your methods section for the logistic regression details a number of normalization steps for the logCPM data prior to model training ("We normalized gene measurements using a series of steps..."). I'm having some trouble finding the corresponding code for this in the repository (in either 2.0_DE.R, 3.0_ML_Training.ipynb, or the util functions). Could you point me to the relevant scripts? Or did you end up using another method for normalization? My apologies if I've missed something!

Best,
David

**Comment by miramou** [comment]
Hi David,

Thanks for your note and kind words!

You can find the code related to pre-processing steps in the class definition for `ML_data` [here](https://github.com/miramou/pe_cfrna/blob/195e6a3ee308fca7e1aefba1c9e0694c90c6d5d7/analysis/util/class_def/ml_obj_classes.py#L113). 

To see what preprocessing steps were used, take a look at `ml_data_kwargs` (reproduced below) in notebook 3.0_ML_Training.pynb. 

`ml_data_kwargs = {'to_norm_to_stable_genes' : True, 
                  'stable_genes' : de_PE.de.loc[de_PE.de.adj_pval > 0.99].index,
                  'to_center' : True, 
                  'to_scale' : True,
                  'impute_dropout' : False
                 }`

These kwargs are passed into the function `training_pipeline` - linked [here](https://github.com/miramou/pe_cfrna/blob/195e6a3ee308fca7e1aefba1c9e0694c90c6d5d7/analysis/util/ml_utils.py#L219). Training pipeline in turn calls `make_train_val_ML_data_obj` - linked [here](https://github.com/miramou/pe_cfrna/blob/195e6a3ee308fca7e1aefba1c9e0694c90c6d5d7/analysis/util/ml_utils.py#L202) - in a loop for each set of filters used during feature selection (hard cutoffs for logFC and CV). 

You'll find the call to instantiate an object of the class ML_data in `make_train_val_ML_data_obj` and you'll see it passes the kwargs defined above and in the 3.0 script. Let me know if you have other questions.

Mira

**Comment by davidwumdphd** [comment]
Hi Mira, 

Amazing, thanks for the clarification! 
In applying your stable gene idea, we noticed that a threshold of adj. P > 0.99 produces thousands of genes in our own cfRNA dataset, compared to the 66 in your dataset. Do you think this would still be reasonable to use as the stable gene set? The number seems quite high so we also considered using some other curated gene list, or even simply using GAPDH, as in your 2018 Science paper on pre-term birth. 

David

**Comment by miramou** [comment]
Hi David,

You could try randomly sampling from that set of 1000 or setting a more stringent threshold (e.g., 0.995). We explicitly did not use GAPDH in the 2018 paper or in this paper as it doesn't serve the same role in cfRNA measurement as it does in the cell. 

In the cell, GAPDH and beta-actin are housekeeping genes and you can safely assume it'd be equivalent across cell populations. But in cfRNA where there are several confounding factors (e.g., we don't know how many cells contributed RNA per individual), GAPDH measurement may not behave the same way. 

Mira
