### ISSUE TITLE
Metadata for gestational age at delivery

### ISSUE THREAD

**Issue by kmfisch** [miramou/pe_cfrna#4]
Hi Dr. Moufarrej,

Thank you for this well curated Github repo. I was wondering if you could please point me to the metadata used in analysis/1_Cohort_Viz.ipynb Cell 2. Based on the README, I  downloaded the metadata provided in BioProject PRJNA792450, but it is missing gestational age at delivery and other clinical data used in this script (Cell 7 and later). Thank you in advance!

Best,

Katie

**Comment by miramou** [comment]
Hi Katie,

Thank you for your interest in our work. We did our best to include whatever metadata we are able to share on a per sample/subject basis via the SRA; however, as you've noted, it does not include all variables listed in 1_Cohort_Viz.ipynb owing to privacy concerns when sharing such data on a per subject basis. The notebook (1_Cohort_Viz) should hopefully give you an overview of what these values were on a cohort basis.

Best,
Mira

**Comment by kmfisch** [comment]
Hi Mira,

Thank you for your rapid response. I am interested in using this dataset as a validation cohort that requires information about which subjects are early onset (<34 weeks) and late onset (>34 weeks) PE. Is it possible to obtain this piece of information (I would be happy to execute a DUA if necessary)? If so, I can directly email you and we can discuss logistics further. Thank you in advance for your consideration!

Cheers,

Katie

**Comment by miramou** [comment]
Hi Katie - Apologies for the delayed response. After some discussion with our clinical team on whether we might be able to disclose a few more metadata features, I plan to update our SRA submission with this information by the end of the week. Will let you know once it's been submitted. You can download from there.

Mira

**Comment by kmfisch** [comment]
Hi Mira,

Thank you so much! I very much appreciate it!

Cheers,

Katie

**Comment by miramou** [comment]
I submitted the update. It should hopefully be up by next week and includes sequencing batch, gestational age at PE onset and gestational age at delivery.
